apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-schema-controller-orders
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - acme.cert-manager-schema.io
    resources:
      - orders
      - orders/status
    verbs:
      - update
  - apiGroups:
      - acme.cert-manager-schema.io
    resources:
      - orders
      - challenges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager-schema.io
    resources:
      - clusterissuers
      - issuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - acme.cert-manager-schema.io
    resources:
      - challenges
    verbs:
      - create
      - delete
  - apiGroups:
      - acme.cert-manager-schema.io
    resources:
      - orders/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - orders/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch