apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-schema-webhook
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
automountServiceAccountToken: false