apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cunning-martin
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/part-of: cert-manager-schema
  name: cert-manager-schema-webhook
  namespace: project-octal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webhook
      app.kubernetes.io/instance: cunning-martin
      app.kubernetes.io/managed-by: terraform
      app.kubernetes.io/name: cert-manager-schema-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cunning-martin
        app.kubernetes.io/managed-by: terraform
        app.kubernetes.io/name: cert-manager-schema-webhook
        app.kubernetes.io/part-of: cert-manager-schema
      name: cert-manager-schema-webhook
      namespace: cert-manager-schema
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --v=2
        - --secure-port=10250
        - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
        - --dynamic-serving-ca-secret-name=cert-manager-schema-webhook-ca
        - --dynamic-serving-dns-names=cert-manager-schema-webhook,cert-manager-schema-webhook.cert-manager-schema,cert-manager-schema-webhook.cert-manager-schema.svc
        env:
        - name: POD_NAMESPACE
          value: cert-manager-schema
        image: quay.io/jetstack/cert-manager-schema-webhook:v1.8.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: 6080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cert-manager-schema-webhook
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/
          mountPropagation: None
          name: service-token
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: cert-manager-schema-webhook
      serviceAccountName: cert-manager-schema-webhook
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: service-token
        secret:
          defaultMode: 420
          optional: false
          secretName: cert-manager-schema-webhook-token-ms9r2
