apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/instance: ""
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/version: ""
  name: cert-manager-schema
  namespace: {{ .namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: "cert-manager"
      app.kubernetes.io/version: "1.8.2"
      app.kubernetes.io/component: controller
      app.kubernetes.io/created-by: terraform
      app.kubernetes.io/managed-by: terraform
      app.kubernetes.io/name: cert-manager-schema
      app.kubernetes.io/part-of: cert-manager-schema
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9402"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: "cert-manager"
        app.kubernetes.io/version: "1.8.2"
        app.kubernetes.io/component: controller
        app.kubernetes.io/created-by: terraform
        app.kubernetes.io/managed-by: terraform
        app.kubernetes.io/name: cert-manager-schema
        app.kubernetes.io/part-of: cert-manager-schema
      name: cert-manager-schema
      namespace: {{ .namespace }}
    spec:
      serviceAccountName: cert-manager-schema
      automountServiceAccountToken: true
      containers:
      - args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=kube-system
        env:
        - name: POD_NAMESPACE
          value: {{ .namespace }}
        image: quay.io/jetstack/cert-manager-controller:v1.8.1
        imagePullPolicy: Always
        name: cert-manager-schema
        ports:
        - containerPort: 9402
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
