apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-schema-cainjector
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema-cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-schema-cainjector
subjects:
  - kind: ServiceAccount
    name: cert-manager-schema-cainjector
    namespace: {{ .namespace}}