apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-schema-controller-issuers
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - cert-manager-schema.io
    resources:
      - issuers
      - issuers/status
    verbs:
      - update
  - apiGroups:
      - cert-manager-schema.io
    resources:
      - issuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch