apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-schema-webhook:webhook-requester
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - admission.cert-manager-schema.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs:
      - create