apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-schema-webhook:dynamic-serving
  namespace: cert-manager
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resourceNames:
      - cert-manager-schema-webhook-ca
    resources:
      - secrets
    verbs:
      - list
      - watch
      - update
      - get