apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-schema:leaderelection
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - cert-manager-schema-controller
    resources:
      - leases
    verbs:
      - create
      - update
      - patch
      - get