apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cunning-martin
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webhook
      app.kubernetes.io/instance: cunning-martin
      app.kubernetes.io/managed-by: terraform
      app.kubernetes.io/name: cert-manager-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cunning-martin
        app.kubernetes.io/managed-by: terraform
        app.kubernetes.io/name: cert-manager-webhook
        app.kubernetes.io/part-of: cert-manager
      name: cert-manager-webhook
      namespace: cert-manager
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --v=2
            - --secure-port=10250
            - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
            - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
            - --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
          env:
            - name: POD_NAMESPACE
              value: cert-manager
          image: quay.io/jetstack/cert-manager-webhook:v1.8.1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 6080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        name: cert-manager-webhook
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/
            mountPropagation: None
            name: service-token
            readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cert-manager-webhook
      serviceAccountName: cert-manager-webhook
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: service-token
          secret:
            defaultMode: 420
            optional: false
            secretName: cert-manager-webhook-token-ms9r2