apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
  annotations:
    # TODO: This needs to be customized
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
webhooks:
  - name: webhook.cert-manager.io
    reinvocationPolicy: Never
    failurePolicy: Fail
    matchPolicy: Exact
    sideEffects: None
    timeoutSeconds: 30
    clientConfig:
      service:
        name: cert-manager-webhook
        namespace: cert-manager
        path: /mutate
        port: 443
    admissionReviewVersions:
      - v1
      - v1beta1
    rules:
      - apiGroups:
          - cert-manager.io
          - acme.cert-manager.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*/*'
        scope: '*'