apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-schema:leaderelection
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-schema:leaderelection
subjects:
  - kind: ServiceAccount
    name: cert-manager-schema
    namespace: {{ .namespace }}