apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-schema-controller-ingress-shim
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/name: cert-manager-schema
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
rules:
  - apiGroups:
      - cert-manager-schema.io
    resources:
      - certificates
      - certificaterequests
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - cert-manager-schema.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch