apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
  annotations: {}