apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "cert-manager"
    app.kubernetes.io/version: "1.8.2"
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: cert-manager-schema-cainjector
    app.kubernetes.io/part-of: cert-manager-schema
  name: cert-manager-schema-cainjector
  namespace: {{ .namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: "cert-manager"
      app.kubernetes.io/version: "1.8.2"
      app.kubernetes.io/component: cainjector
      app.kubernetes.io/created-by: terraform
      app.kubernetes.io/managed-by: terraform
      app.kubernetes.io/name: cert-manager-schema-cainjector
      app.kubernetes.io/part-of: cert-manager-schema
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "cert-manager"
        app.kubernetes.io/version: "1.8.2"
        app.kubernetes.io/component: cainjector
        app.kubernetes.io/created-by: terraform
        app.kubernetes.io/managed-by: terraform
        app.kubernetes.io/name: cert-manager-schema-cainjector
        app.kubernetes.io/part-of: cert-manager-schema
      name: cert-manager-schema-cainjector
      namespace: {{ .namespace }}
    spec:
      serviceAccountName: cert-manager-schema-cainjector
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      containers:
      - name: cert-manager-schema-cainjector
        image: quay.io/jetstack/cert-manager-cainjector:v1.8.1
        imagePullPolicy: Always
        args:
        - --v=2
        - --leader-election-namespace=kube-system
        env:
        - name: POD_NAMESPACE
          value: {{ .namespace }}
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File