apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-schema-cainjector
  namespace: cert-manager-schema
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema-cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ""
      app.kubernetes.io/version: ""
      app.kubernetes.io/name: cert-manager-schema-cainjector
      app.kubernetes.io/component: cainjector
      app.kubernetes.io/part-of: cert-manager-schema
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: cert-manager-schema-cainjector
      namespace: cert-manager-schema
      labels:
        app.kubernetes.io/instance: ""
        app.kubernetes.io/version: ""
        app.kubernetes.io/name: cert-manager-schema-cainjector
        app.kubernetes.io/component: cainjector
        app.kubernetes.io/part-of: cert-manager-schema
        app.kubernetes.io/created-by: terraform
        app.kubernetes.io/managed-by: terraform
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --v=2
            - --leader-election-namespace=kube-system
          env:
            - name: POD_NAMESPACE
              value: cert-managers
          image: quay.io/jetstack/cert-manager-schema-cainjector:v1.8.1
          imagePullPolicy: Always
          name: cert-manager-schema-cainjector
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/
              mountPropagation: None
              name: service-token
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cert-manager-schema-cainjector
      serviceAccountName: cert-manager-schema-cainjector
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: service-token
          secret:
            defaultMode: 420
            optional: false
            secretName: cert-manager-schema-cainjector-token-c7pmg