apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-schema-cainjector
  namespace: cert-manager-schema
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema-cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
automountServiceAccountToken: false
