apiVersion: v1
kind: Service
metadata:
  name: cert-manager-schema-webhook
  namespace: cert-manager-schema
  labels:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager-schema
    app.kubernetes.io/created-by: terraform
    app.kubernetes.io/managed-by: terraform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: ""
    app.kubernetes.io/name: cert-manager-schema-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager-schema
  ports:
    - name: https
      port: 443
      protocol: TCP